# Generated by Django 3.2.17 on 2023-03-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='students',
        ),
    ]
