# Generated by Django 3.2.17 on 2023-03-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='_classes',
            field=models.ManyToManyField(blank=True, help_text='Select a class for this student', to='attendance.Class'),
        ),
    ]
