# Generated by Django 3.2.17 on 2023-03-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_student__classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WifiRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=17)),
            ],
        ),
        migrations.AddField(
            model_name='attendanceform',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
